# PostgreSQL Configuration for Render
spring.datasource.url=jdbc:postgresql://dpg-d6m3j6a4d50c73ckocng-a.singapore-postgres.render.com/expenseanalyticsservice?sslmode=require
spring.datasource.username=expenseanalyticsservice_user
spring.datasource.password=B4Ybqc49Vs0tuUExV5yepAC3AT18MxNM
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Connection Pool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5